# Generated by Django 4.2.30 on 2026-08-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.JSONField(default=list, help_text='Entidades UML en formato React Flow')),
                ('edges', models.JSONField(default=list, help_text='Relaciones entre entidades en formato React Flow')),
                ('viewport', models.JSONField(default=dict, help_text='Posicion y zoom del canvas')),
            ],
            options={
                'db_table': 'diagrama',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_base', models.CharField(help_text='Ej: com.example.salud', max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
    ]
