# Generated by Django 4.2.30 on 2026-08-31 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagrama',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagrama', to='projects.proyecto'),
        ),
    ]
