# Generated by Django 4.2.30 on 2026-09-21 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_diagrama_id_alter_proyecto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='proyectos_colaborando', to=settings.AUTH_USER_MODEL),
        ),
    ]
